### ISSUE TITLE
wrong username / password

### ISSUE THREAD

**Issue by mimikm** [CJNE/ha-myenergi#101]
Hi,

Having trouble logging in. Integration downloads correctly but when adding I cannot log in.

Regards

**Comment by G6EJD** [comment]
Things to check:
If using an iPhone it usually adds a space to the Username and or password, check your credentials.
Using the new App 2.0 reset your password.

**Comment by mimikm** [comment]
Tried as above. Still no luck. Credentials ok. Changed email, password.

**Comment by G6EJD** [comment]
And using the Hub serial number?

**Comment by colinhatfield** [comment]
I get the same error when setting up: "Username/Password is wrong."

I've tried both my username (E-mail address) and the hub serial, I'm using the password that I've just successfully logged into https://myaccount.myenergi.com with.

Any advice?

**Comment by mimikm** [comment]
> And using the Hub serial number?

Absolutely, tired all combinations

**Comment by G6EJD** [comment]
Did you restart HA via he restart Host?

**Comment by mimikm** [comment]
I have installed integration through HACS, then added integration through UI, then "Username/Password is wrong." 

Logs say nothing apart from:
`2022-02-21 12:10:18 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration myenergi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

**Comment by spirit8000** [comment]
Hi. I'm having the same issue with v0.0.17. Email and password definitely correct, no issue logging in to iPhone app or via a browser. Behaviour seems to be the same as described here: "https://myenergi.info/viewtopic.php?p=46485#p46485".  Tried reinstalling the myenergi integration via HACS several times, both v0.0.16 and v0.0.17. Restarts in between. Installation successful each time, same username/password error every time. I've also changed to a different email account and reset the password.

Can you actually log in with the hub serial number? Appreciate this may have been the case in the past, having only got the hub a couple of days ago, but if you try to log in to https://myaccount.myenergi.com/ there is only an email address option, same for the current iPhone app. So I wonder if their authentication has changed / is changing? Or equally perhaps I'm missing something. 

Happy to provide logs, test stuff, fudge code etc. Cheers!

**Comment by mimikm** [comment]
> Have you tried the manual install method in the readme?

In logs
`2022-02-21 15:21:46 ERROR (SyncWorker_1) [homeassistant.loader] Error parsing manifest.json file at /config/custom_components/myenergi/manifest.json: Expecting value: line 7 column 1 (char 6)`

when I try add integration in UI:

`Error
Config flow could not be loaded: [object Object]`

**Comment by spirit8000** [comment]
> Have you tried the manual install method in the readme?

Hi, I've just tried the manual installation. The installation seemed fine but still the same behaviour when trying to log in with the myenergi creds, both using email or hub serial number. 

Just to confirm I did a restart following copying the folder in. 

Is there any further information I can provide to help trouble shoot, or anything else I can try at this point?

**Comment by CJNE** [comment]
The username to use is the hub serial number, it will not work with an email address.
The password does not have to be the same as you use for the "myenergi account" login.
It's the password you created when setting up the app for the first time.

Installation method should not make a difference, I suspect it's just that the wrong username and password is being used.

**Comment by mimikm** [comment]
> The username to use is the hub serial number, it will not work with an email address. The password does not have to be the same as you use for the "myenergi account" login. It's the password you created when setting up the app for the first time.
> 
> Installation method should not make a difference, I suspect it's just that the wrong username and password is being used.

Unfortunately, nothing works.
Old or new password. Unless the password is a registration code from Zappi charger

**Comment by spirit8000** [comment]
> The username to use is the hub serial number, it will not work with an email address. The password does not have to be the same as you use for the "myenergi account" login. It's the password you created when setting up the app for the first time.
> 
> Installation method should not make a difference, I suspect it's just that the wrong username and password is being used.

Hi,

Thanks for the reply, appreciate you taking the time. 

Understood ref the hub serial number, I've tried with that, copy and paste straight from my myenergi account and checked for spaces before or after. 

I'm confused about the password though. The app logs in with the same password as I'd use for https://myaccount.myenergi.com/login. I've just reset it from my phone as a test (using the myenergi IOS app, v2.0.7), then logged in to https://myaccount.myenergi.com/login with the new password from a browser on my laptop. That works fine, but then retried the integration setup and still get the "Username/Password is wrong." error using the serial number (8 digit numeric) and new password. 

Where you say "It's the password you created when setting up the app for the first time." - I don't remember setting any other password initially, plus I've just reset it with the app. Are we talking about the same app?

**Comment by spirit8000** [comment]
Incidentally, the current app and the current website don't allow logging in using the hub ID, only the email address.

Also, in October 2021, I've noticed this comment from a myenergi representative in their forum:

"We're working hard to get rid of the app password so there is just the myenergi account, with the option for a self service password reset.
It's close but..."

https://myenergi.info/registered-hub-password-now-invalid-cannot-access--t940.html

People reporting similar problems here: https://myenergi.info/viewtopic.php?p=46485#p46485

I'm quite confident I didn't have to set a password. Is it possible the service behind has changed / is changing at least for new users like myself?

**Comment by G6EJD** [comment]
What is the logbook reporting, if there was a username password error it would be reported there?

**Comment by mimikm** [comment]
> What is the logbook reporting, if there was a username password error it would be reported there?

Are we talking about HA log? Nothing there, unfortunately.

**Comment by nabjoern** [comment]
Unfortunately I have the same problems as spirit8000 and mimikm. Today I activated the hub and updated my zappi. It all worked without any problems.
Unfortunately, I can't get them integrated in HA. Also get the error:
Username/Password is wrong.

**Comment by G6EJD** [comment]
Are you using just the Hub serial number excluding the prefix? A12345678 is 12345678

**Comment by mimikm** [comment]
> Are you using just the Hub serial number excluding the prefix? A12345678 is 12345678

Yes, happy to arrange zoom call for example so you can try it yourself. maybe it will give you an idea.

**Comment by benjeh32** [comment]
+1 here. Hub serial (exactly as it appears on the base of the hub and which was successfully used to set things up) plus my myenergi account password fails login when setting up the integration. I have tried resetting this password both from the app as well as from the web.

The only password I have is my account password. I had my Zappi installed today and when setting up the app (Android, for what it is worth) I only had to create a myenergi account with email/password. That combination also logs me in to https://myaccount.myenergi.com. As we added the Hub into the app the installer said "you will have to choose a password" but the app did not ask us for this and everything has been working fine without one (until trying to use the API of course).

I tried to directly authenticate using pymyenergi (in case it was an integration issue) but login still fails. Debug logs from pymyenergi (user/pass is set up in ~/.myenergi.cfg):
```
>myenergi -d list
DEBUG:pymyenergi.client:Refreshing data for all myenergi devices
DEBUG:pymyenergi.connection:Get Myenergi base url from director
DEBUG:httpx._client:HTTP Request: GET https://director.myenergi.net/cgi-jstatus-E "HTTP/1.1 401 Unauthorized"
DEBUG:httpx._client:HTTP Request: GET https://director.myenergi.net/cgi-jstatus-E "HTTP/1.1 401 Unauthorized"
INFO:pymyenergi.connection:Updated myenergi active server to https://s18.myenergi.net
DEBUG:pymyenergi.connection:GET /cgi-get-app-key- https://s18.myenergi.net/cgi-get-app-key-
DEBUG:httpx._client:HTTP Request: GET https://s18.myenergi.net/cgi-get-app-key- "HTTP/1.1 401 Unauthorized"
DEBUG:httpx._client:HTTP Request: GET https://s18.myenergi.net/cgi-get-app-key- "HTTP/1.1 401 Unauthorized"
DEBUG:pymyenergi.connection:GET status 401
Wrong username or password
```

**Comment by CJNE** [comment]
It starts to sound like they might have changed something for new accounts...
I will try to reach out to them on the forum and see if we can get some clarification.

**Comment by CJNE** [comment]
This might be a clue:
https://myenergi.info/myenergi-app-version-2-0-x-t5070.html?sid=d5b780cf1b023c1cd02a14f1b6b1a7ba

**Comment by nabjoern** [comment]
Tried it again today. Restarted everything etc. Still not working. Hope it will be fixed sometime soon :-)

**Comment by CJNE** [comment]
I posted in the forum asking for advice. It might help to pitch in there so that they see that it's a real problem: https://myenergi.info/viewtopic.php?p=48889#p48889

**Comment by mjdyson** [comment]
A brand new user here (installed on Friday). I have been struggling to set up the integration until I received an API from myenergi. Username was the hub serial (without the hub prefix), password was the API key. 

See post 
https://myenergi.info/api-keys-t5185.html

**Comment by CJNE** [comment]
> A brand new user here (installed on Friday). I have been struggling to set up the integration until I received an API key from myenergi. Username was the hub serial (without the hub prefix), password was the API key.
> 
> See post https://myenergi.info/api-keys-t5185.html

Thanks for the info! I think this issue is resolved, will update the docs.
