### ISSUE TITLE
Resetting credentials

### ISSUE THREAD

**Issue by aceshigh84** [CJNE/ha-myenergi#128]
Hi,

After resetting my hub and other devices and repairing everything I have not been able to get this integration to work again.

The error shown on the integration page is retrying setup, I have also attempted configure and system options but neither gives an option to add or change the username or password.

The next logical step is to delete the integration and then install it again but I do not want to do this if it means losing the entities and related information.

Please advise how to reset the credentials so that I can get the integration authenticated again.

Thank you.

**Comment by G6EJD** [comment]
I reset my integration yesterday and everything works as expected. In fact I deleted the integration then reinstalled entered my credentials all all data remained.
What’s changed is MyEnergi has changed their authentication and now you have o generate an API key via their App, then use your Hub serial number as the username and API key as the password.

**Comment by jumoog** [comment]
maybe authentication should be part of the options. I can't reset my integration

**Comment by G6EJD** [comment]
You can delete it though, that effectively resets everything then asks for credentials again.

**Comment by G6EJD** [comment]
I deleted mine and all the sensors remained. No names are changed, so dashboards remained unaltered.

**Comment by aceshigh84** [comment]
Thank you. I did as suggested and deleted the integration and then added it again, prompted for credentials and used the hub serial and API key, the integration now works again and I didn't lose any previous entities or setup.

Cheers.

**Comment by G6EJD** [comment]
That's good, you can close the issue now.
