### ISSUE TITLE
Authentication rejected

### ISSUE THREAD

**Issue by glyn12** [CJNE/ha-myenergi#144]
I have just installed via HACS, however, using the following combinations, I can't get past the authentication screen.

I have seen on the myenergi forum similar threads.  But I 100% have my correct hub id (copy and pasted it from the myenergi website, as well as typing it in directly), and I have tried several generations of API key, but every time I get "Hub serial or API key is wrong."

Happy to try to help debug!

**Comment by G6EJD** [comment]
Its your data not the integration, its almost always a typographical error, try copy and paste the API key to reduce errors.

**Comment by glyn12** [comment]
I solved it, it wasn't a typo, I was already copying and pasting data.

The problem is in https://github.com/CJNE/pymyenergi/blob/main/pymyenergi/connection.py - or maybe it's actually on MyEnergi's side.  It was always trying to authenticate me on the s9 server (which I believe is down to their return from the director).  However, whilst the s9 server rejected my credentials, the s18 server accepted them (I guess I've been moved to their "cloud" server, which I understand the s18 is).  Making hacky adjustments in connnection.py to force it to use s18 enabled it to work.

Unfortunately, the attempt to move to the next server in connection.py doesn't appear to work, as it's reset each time one tries to authenticate from HA.

**Comment by glyn12** [comment]
Closing the issue as it's really an underlying myenergi issue / enhancement, although, I believe it will cause an issue for newer myenergi customers who start on the s18 server.

**Comment by lorrainem77** [comment]
Sorry to jump on a closed issue, but I think I have the same problem. This integration has been working pefectly for months, even through being on a myenergi Project Fusion trial, which moved me onto a different server. They appear to have moved the server I'm on again yesterday / today, which resulted in an error on the integration, I tried to add it again and I'm getting an authetication error (copying and pasting the API key). I dont know where to locate the connection.py file to make "hacky adjustments". Can anyone help me please?
