### ISSUE TITLE
Can't find configuration section/popup/login

### ISSUE THREAD

**Issue by Alexanderis** [CJNE/ha-myenergi#149]
Home Assistant Core 2022.5.3
Home Assistant Supervisor 2022.05.0
Home Assistant OS 7.6
Kernel version 5.10.108
Agent version 1.2.1
Path to configuration.yaml: /config

HACS - 1.24.5
ha-myenergi - 0.0.18

After installing myenergi through HACS there is no configuration option to be found.

Where exactly does the configuration take place and how are the user/api key configured?

**Comment by G6EJD** [comment]
When you install the integration via Settings, Devices & Services, then +Add Integration search for myenergi after the install it will prompt for hub serial and api key

**Comment by Alexanderis** [comment]
Brand new to Home Assistant and figured the issue just after opening tis ticket.
Thank you for the reply though, much appreciated! I've set it up and works nicely!
