### ISSUE TITLE
Remove Harvi device

### ISSUE THREAD

**Issue by erikhagemeijer** [CJNE/ha-myenergi#166]
I suddenly have 2 harvi's in my setup. If I log in into my Myenergi account I can see the second harvi also, so probably they screwed up. I could remove the harvi there, but how do I remove it from my Home Assistant setup?

**Comment by CJNE** [comment]
You could go to Configuration->Devices and find the duplicate Harvi, click it and then the pen icon and disable it.

**Comment by erikhagemeijer** [comment]
Hello Johan,

Thanks for your nice Add-on for Home Assistant.

I’ve disabled the device, but in the sensor.myenergi_<hubname>_power_generation entity the production of the ghost harvi is still added.
Could it be that the add on doesn’t check if an entity is disabled?

Regards, Erik.

**Comment by JanDetrez** [comment]
Have a similar issue: had 2 harvi's, but removed one physically and also in the MyEnergi app. However the ghost harvi still appears in the Hassio plugin, also after removing and re-adding the plugin. I can disable the Harvi, but the power reported by the ghost harvi is still added to the overall power use/consumption. Perhaps I need to be patient for the API to sync the device configuration change?

Did you find a solution?

**Comment by erikhagemeijer** [comment]
Hi,

I contacted MyEnergi and they removed the ghost harvi.

Greatings, Erik.

**Comment by CJNE** [comment]
The solution to this is the contact MyEnergi and have them remove the ghost, thanks @erikhagemeijer
