### ISSUE TITLE
Failure to start with Home Assistant 2022.7.0

### ISSUE THREAD

**Issue by mfschumann** [CJNE/ha-myenergi#179]
After updating to Home Assistant 2022.7.0 I get the following error and no myenergi sensors work anymore. I suspect this to be related to the upgrade to python 3.10 in Home Assistant 2022.7.0.

`Setup failed for custom integration myenergi: Unable to import component: No module named 'pymyenergi'`

I am happy to provide more information if needed.

**Comment by mfschumann** [comment]
I think the problem could be caused by a regression in `homeassistant.util.package` which I reported in [this issue](https://github.com/home-assistant/core/issues/74597). So presumably there is not much that can be done on the end of this integration.

**Comment by CJNE** [comment]
Thanks for reporting this! I had a look at your reported issue and it seems to have been closed, is the issue resolved?

**Comment by mfschumann** [comment]
Yes, HA 7.4 fixes the issue for me. Note however that the issue vanished only after an additional restart of Home Assistant after the restart during upgrade.
