### ISSUE TITLE
Deprecated methods NumberEntity

### ISSUE THREAD

**Issue by Nightraider89** [CJNE/ha-myenergi#188]
This Error Popped up In the HA Log.

custom_components.myenergi.number::HeaterPriorityNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

custom_components.myenergi.number::DevicePriorityNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

custom_components.myenergi.number::MinimumGreenLevelNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

**Comment by gertjanstulp** [comment]
The issue is caused by some property deprecations in a recent update, see https://developers.home-assistant.io/blog/2022/06/14/number_entity_refactoring. I will try to create a PR to fix this.
