### ISSUE TITLE
Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11

### ISSUE THREAD

**Issue by thunder2k** [CJNE/ha-myenergi#21]
Hi,
I found the following in the logs and want to bring it to your attention :)
## Version of the custom_component

0.0.11
## Configuration
Installed from HACS

## Describe the bug
I saw the following coming in my logs and want to give you a heads up so you can give it a look before November otherwise it ill break the integration.

## Debug log

```text

Entity sensor.myenergi_home_grid_import_today_cost (<class 'homeassistant.components.energy.sensor.EnergyCostSensor'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+energy%22

```

**Comment by CJNE** [comment]
Thanks @thunder2k, that warning actually comes from the built in Home Assistant energy component, they will probably fix that in the next release.
