### ISSUE TITLE
Energy sensor for home usage?

### ISSUE THREAD

**Issue by yacoob** [CJNE/ha-myenergi#215]
As far as I can tell, there's only one sensor available for Home power usage: `sensor.myenergi_hub_home_consumption`. Is there a way to get the matching energy sensor, for energy used by home directly? Or is adding your own `integration` sensor in HA the recommended way to go?

**Comment by CJNE** [comment]
Sorry for the very late response! Yes, the recommended approach is to create your own sensor based on the "raw" values from this integration.
