### ISSUE TITLE
Error occurred loading configuration flow

### ISSUE THREAD

**Issue by tredmanz** [CJNE/ha-myenergi#224]
I have a new installation running in HomeAssistant Core Docker on OMV (on a raspberry PI 4). Previously had it working fine with a similar installation on Unraid (though with x64).

Got integration installed via HAC and checked the custom_components directory - its correct.

On enabling it with HA I get:

Logger: homeassistant.config_entries
Source: config_entries.py:796
First occurred: 11:04:51 AM (2 occurrences)
Last logged: 11:05:15 AM

Error occurred loading configuration flow for integration myenergi: No module named 'pymyenergi'

Is there a compatibility issue with the installation/architecture, or is it something else?

**Comment by RobM83** [comment]
I'm currently having the same problem, before I dive into it, were you able to solve it ?

**Comment by G6EJD** [comment]
Did you try a restart?

**Comment by RobM83** [comment]
Wow, no apparently I did only a restart after the HACS installation and not the myenergy plugin.

Sorry for the inconvenience, it seems to work now.

I think this issue can be closed ?
