### ISSUE TITLE
Server request problem

### ISSUE THREAD

**Issue by Ulrar** [CJNE/ha-myenergi#229]
## Version of the custom_component

0.0.20, latest from hacs

## Describe the bug
Hi,

My internet went out for a few days, and now that it's back this component is the only one that won't load properly.
The error below doesn't give much information, no idea what's wrong but the myenergi mobile app is working fine and reporting data, so presumably my hub has connected back fine.
Since last night I tried a few times reloading the integration, disabling / enabling it and restarting HA all give the same error :

```text

Logger: pymyenergi.connection
Source: custom_components/myenergi/__init__.py:90
Integration: myenergi ([documentation](https://github.com/cjne/ha-myenergi), [issues](https://github.com/cjne/ha-myenergi/issues))
First occurred: 11:36:53 AM (6 occurrences)
Last logged: 11:39:36 AM
Myenergi server request problem

```

I had a look at the myenergi forum and I don't see any obvious signs of their service being disrupted, but who knows.

Thanks

**Comment by G6EJD** [comment]
Highly unlikely to be a error of this integration. What’s happened is your server connection has changed or if you have had the service running for some time you now need an API key, do you use the Hub Serial number and API key or you can use any MyEnergi device serial number plus API key. They (ME) have been migrating customers to new servers recently

**Comment by Ulrar** [comment]
I feel like I've done that, but I'm not sure.
How do you go about adding that in ? Doesn't seem to be an option in the integration configuration.

**Comment by Ulrar** [comment]
Aha, figured it out, disabling ad blocking in pi hole for the setup seems to solve it.
I don't know what domain is getting blocked and by what list, but something is so if anyone else gets here with the same error there you go.
I've re-enabled it afterwards and I'm not seeing anything get blocked so presumably it's just during the setup, but we'll see
