### ISSUE TITLE
Zappi/Eddi/Hub firmware versions in sensors

### ISSUE THREAD

**Issue by markcocker** [CJNE/ha-myenergi#237]
**Is your feature request related to a problem? Please describe.**
There is no push notification when new Zappi/Eddi/Hub firmware versions are available.

**Describe the solution you'd like**
I would like a sensor (or attribute on another sensor) for each myenergi device that provides the installed firmware version, the serial number, and if possible the latest firmware version so I can setup HA alerts.

Alternatively, this could be integrated with the Home Assistant updates for devices - https://www.home-assistant.io/integrations/update/

**Describe alternatives you've considered**
I periodically look at either the device display or https://myaccount.myenergi.com/location#products and then compare this to the table in https://support.myenergi.com/hc/en-gb/articles/360020109017-Current-firmware-versions-updating-your-firmware 

**Additional context**
The myenergi RESTI API detailed at https://github.com/twonk/MyEnergi-App-Api shows:
"fwv" = firmware version
"sno" = serial number

We could raise an issue on the myenergi forums to add an API to return the latest firmware versions.

**Comment by JasSmiths** [comment]
+1 This would be a great addition

**Comment by LeiChat** [comment]
Could we use the newAppAvailable and/or new BootloaderAvailable boolean properties?
https://s18.myenergi.net/cgi-jstatus-* 

`[{"eddi":[{"sno":SERIAL_NO,"dat":"01-02-2023","tim":"23:16:45","ectt1":"Internal Load","ectt2":"Grid","ectt3":"None","bsm":0,"bst":0,"cmt":254,"dst":1,"div":0,"frq":50.04,**"fwv":"3202S4.097"**,"gen":-12,"grd":-6,"pha":1,"pri":1,"sta":1,"tz":0,"vol":2411,"hpri":1,"hno":1,"ht1":"Tank 1","ht2":"None","r1a":0,"r2a":0,"rbc":0,"tp1":127,"tp2":127,"newAppAvailable":false,"newBootloaderAvailable":false,"batteryDischargeEnabled":false}]},{"zappi":[{"sno":SERIAL_NO,"dat":"01-02-2023","tim":"23:16:45","ectp2":1,"ectp3":-12,"ectt1":"Internal Load","ectt2":"Grid","ectt3":"Generation","bsm":0,"bst":0,"cmt":254,"dst":1,"div":0,"frq":50.04,**"fwv":"3562S4.525"**,"gen":-12,"grd":-6,"pha":1,"pri":2,"sta":1,"tz":0,"vol":2417,"bss":0,"lck":16,"pst":"B1","zmo":3,"pwm":1200,"zs":1026,"rdc":1,"rac":4,"zsh":4,"zsl":2,"ectp4":318,"ectt4":"AC Battery","ectt5":"None","ectt6":"None","newAppAvailable":false,"newBootloaderAvailable":false,"beingTamperedWith":false,"batteryDischargeEnabled":false,"mgl":100,"sbh":17,"sbk":5}]},{"harvi":[]},{"asn":"s18.myenergi.net","fwv":"3401S4.525","vhub":1}]`
