### ISSUE TITLE
Re-enter API code - where?!

### ISSUE THREAD

**Issue by jt1971** [CJNE/ha-myenergi#239]
I'm sorry to ask such a simple question, but I cannot find the answer.

I'e had to re-issue the API code on the myenergi website.  I'm struggling to find where I can update Home assistant with the correct code.  Any help appreciated.  I'd rather not have to remove and reinstall Myenergi.

**Comment by G6EJD** [comment]
If you go to add-on, remove the integration and then add it back it will prompt you during install for the username and password again then all entries will return as before and your dashboard will resume.

**Comment by G6EJD** [comment]
Shouldn’t you close this now?
