### ISSUE TITLE
Repo not found

### ISSUE THREAD

**Issue by doddyprodger** [CJNE/ha-myenergi#25]
## Configuration

```yaml
Add your logs here.
```

## Describe the bug

After installation of 0.14 unable to find Repo. The Repo directory is stated as "https://github.com/cjne/myenergi/releases", rather than "https://github.com/CJNE/ha-myenergi"

## Debug log

```text

Add your logs here.

```

**Comment by CJNE** [comment]
Thanks for reporting this, will be fixed in next release!

**Comment by doddyprodger** [comment]
Thanks Johan :)
