### ISSUE TITLE
charges added

### ISSUE THREAD

**Issue by tomdh76** [CJNE/ha-myenergi#29]
Thx for this nice integration!

I am trying to get an overview of all charges added to the EV. I now use the "myenergi_zappi_charge_added..". This show the last added session but this remains this number until a next charge session. So in grafana I see a lot of same numbers over time Is it possible that this sensor resets to 0 after it has been written to the database? Or do you have another way to keep track of the kwh added?

**Comment by CJNE** [comment]
Yes this sounds like a good change, charge added today should reset for each day. I'll change from a cumilative counter to a normal value.

**Comment by G6EJD** [comment]
> Thx for this nice integration!
> 
> I am trying to get an overview of all charges added to the EV. I now use the "myenergi_zappi_charge_added..". This show the last added session but this remains this number until a next charge session. So in grafana I see a lot of same numbers over time Is it possible that this sensor resets to 0 after it has been written to the database? Or do you have another way to keep track of the kwh added?

You can close this now, it’s resets each day
