### ISSUE TITLE
Please add PWM number to the sensor list

### ISSUE THREAD

**Issue by guy-BW** [CJNE/ha-myenergi#302]
**Is your feature request related to a problem? Please describe.**

I have an issue with my car only charging at a lower rate, I've been advised to monitor the PWM value to determine what the communication is reporting when requesting the charge levels. Tracking this number should help in nailing this down.

**Describe the solution you'd like**
Please add the PWM sensor value which is being reported in the Zappi API.

**Describe alternatives you've considered**

**Additional context**

**Comment by G6EJD** [comment]
I’ve just been through the API and it does not report PWM.

Where did you see PWM in the API?

**Comment by guy-BW** [comment]
Using this URL "https://s18.myenergi.net/cgi-jstatus-Z"

I get back this JSON dump, which appears to show the PWM amongst other metrics.

`{
    "zappi": [
        {
            "sno": xxxxx,
            "dat": "15-01-2023",
            "tim": "17:58:23",
            "ectp2": 4571,
            "ectt1": "Internal Load",
            "ectt2": "Grid",
            "ectt3": "Generation",
            "bsm": 0,
            "bst": 0,
            "cmt": 253,
            "dst": 1,
            "div": 0,
            "frq": 49.92,
            "fwv": "3562S4.246",
            "grd": 4577,
            "pha": 1,
            "pri": 2,
            "sta": 1,
            "tz": 0,
            "vol": 2433,
            "che": 0.3,
            "bss": 0,
            "lck": 31,
            "pst": "A",
            "zmo": 3,
            "pwm": 1200,
            "zs": 256,
            "rdc": 1,
            "rac": 4,
            "zsh": 1,
            "ectt4": "None",
            "ectt5": "None",
            "ectt6": "None",
            "newAppAvailable": false,
            "newBootloaderAvailable": false,
            "beingTamperedWith": false,
            "batteryDischargeEnabled": false,
            "mgl": 80,
            "sbh": 17,
            "sbk": 5
        },
        {
            "sno": xxxxx,
            "dat": "15-01-2023",
            "tim": "17:58:25",
            "ectp2": 4683,
            "ectt1": "Internal Load",
            "ectt2": "Grid",
            "ectt3": "None",
            "bsm": 0,
            "bst": 0,
            "cmt": 254,
            "dst": 1,
            "div": 0,
            "frq": 49.92,
            "fwv": "3562S4.246",
            "grd": 4577,
            "pha": 1,
            "pri": 1,
            "sta": 1,
            "tz": 0,
            "vol": 2418,
            "bss": 0,
            "lck": 31,
            "pst": "B1",
            "zmo": 3,
            "pwm": 1200,
            "zs": 1026,
            "rac": 3,
            "rrac": -1,
            "zsh": 4,
            "zsl": 2,
            "ectt4": "None",
            "ectt5": "None",
            "ectt6": "None",
            "newAppAvailable": true,
            "newBootloaderAvailable": true,
            "beingTamperedWith": false,
            "batteryDischargeEnabled": false,
            "mgl": 90,
            "sbh": 7,
            "sbk": 40,
            "sbm": 15
        }
    ]
}
`

**Comment by CJNE** [comment]
Perhaps this is only reported by newer version Zappi's?

**Comment by guy-BW** [comment]
Indeed this is a Zappi 2.1 running version 246

**Comment by CJNE** [comment]
I'm looking into adding the new values, are there any other new value that might be useful?
Should PWM be scaled somehow, or is 1200 the real value? (perhaps divide by 100?).

**Comment by CJNE** [comment]
Looks like this is a percentage, so I'm dividing by 100.

**Comment by G6EJD** [comment]
Yes PWM appears to be in centi-percent so 1200 is 12%

**pt1** and **pt2** are the temperature readings from the PT1000 thermometers used in the Eddi Relay boards e.g. "pt1":55,"pt2":60, the values are in degrees C

**hsk** is the heatsink temperature of the Eddi e.g. "hsk":414, the result is in deci-degrees so 414 is 41.4 degrees C

**Comment by CJNE** [comment]
Thanks @G6EJD, adding them to the python lib and I'll make sensors from them in HA.

**Comment by G6EJD** [comment]
The only uncertainty is whether the API returns these values for the older devices pre 2.1, but if the json decoder returns a 0 if not present then this factor can be ignored.

**Comment by CJNE** [comment]
I'll make it handle missing properties gracefully then, so that it will work even if they are missing. Do you know if the Eddi have the "newBootloaderAvailable" property like the Zappi?

**Comment by G6EJD** [comment]
Unfortunately not as there has been no update for the Eddi v2 for some time, but I expect the Eddi v2.1 with in-built Hub and WiFi to need a new Bootloader as they are using the ESP32 device, although I don't know why they call it a bootloader, it may be for consistency with the older products screen name for the same function.

**Comment by CJNE** [comment]
Thanks @G6EJD !
