### ISSUE TITLE
Eddi "total kW" entity (grid + green)

### ISSUE THREAD

**Issue by BifferPAG** [CJNE/ha-myenergi#327]
Thank you for making this great integration I stumbled across it recently and it's really useful.

Is the avaliblecin the myenergi api an entity to give us the total current kW value (i.e a sum of the green kW + grid kW values) , I have a need to create an action to pause (stop) the eddi when the total kW value exceeds 10kW otherwise the PRV on my unvented water cylinder blows and dumps alot of the hot water from cylinder.

Im not a programmer so I can't understand how to take the two existing seperate kW entities that already exist in this integration and add them together and then make some code from that to trigger the action to stop the eddi.

Many thanks.

**Comment by olej24** [comment]
You should be able to combine the two with a Group Helper

**Comment by CJNE** [comment]
Good suggestion @olej24 , does would best be done in Home Assistant. Did you get it working @BifferPAG ?
