### ISSUE TITLE
Mg ZS EV sets status to Charge complete after solar 

### ISSUE THREAD

**Issue by newbuilder22** [CJNE/ha-myenergi#334]
Not sure if a debug would help here. I know it is an MG issue but wondered if it could be fooled.

situation : After an episode of solar charge MG sends charge complete command to zappi.

problem: scheduled chargers do not take place as car has sent complete command.

solution. To go into car app and restart charge request.

Automated solution request? : can one of the sensors be forced to see the car as disconnected and then after a few minutes reconnect, causing a reunification process?

**Comment by a-wolter** [comment]
This is definitely not related to the integration or the zappi. It’s the car that is sending the status and the only way would be resetting the CP connection. I think changing the status to stopped and back will not help. At least with the zappi 2 here this is not working. This might be different with different hardware versions of the zappi. 
what zappi does, as soon as the status is set to completed, is delivering power anytime even if the zappi is set to eco+
so if the MG is set to charge at a specific time this could be a workaround - but zappi will deliver full charging power even if there is no solar power

**Comment by newbuilder22** [comment]
> Does it work to send stop charge and then set it to fast from the app? I'm afraid this component cannot do anything beyond what can be done from the app, but it that works it can be automated.

This does work but often needs a stop command sent for a length of time not just a few seconds or minutes. 

There are times where I have to manually tell the car to charge but not as many as there were. I just wish a reliable mg integration was available to help. I can view the car in HA but can’t make changes to the charging status.
