### ISSUE TITLE
Zappi -Charge added today

### ISSUE THREAD

**Issue by SteveBrailsord** [CJNE/ha-myenergi#335]
I can see a sensor for Charge added this session, is there one for Charge added today please?
If not could one be made ?

**Comment by CJNE** [comment]
What this component aims to do is to make all the data we can get from the devices available to Home Asisstant. Once there you have a lot of possibilities to transform and create your own sensors based on this. 
What you describe sounds like it should be achievable by adding a Utility Meter sensor using the the charge added this session as input:
https://www.home-assistant.io/integrations/utility_meter/

**Comment by CJNE** [comment]
Have a look at #342 for an example of how this can be done.
