### ISSUE TITLE
Does this speak to myenergi cloud, or directly to the myenergi hub?

### ISSUE THREAD

**Issue by SteveBrailsord** [CJNE/ha-myenergi#336]
How can you speed up the response ?

**Comment by G6EJD** [comment]
Directly with the ME servers.
If your trying to change modes or control a device then poor performance is a function of a poor radio signal between devices.

**Comment by SteveBrailsord** [comment]
I don’t have an issue with control, but all my other sensors are real time
and when integrated with my energi the lag throws all the figures off until
my energy catches up

**Comment by LeiChat** [comment]
Quite a round trip for the data, going up from your zappi/eddi to the myenergi cloud servers and back down.
Might be worth looking at a something like the Shelly Pro 3EM if myenergi is your only source of energy data.
https://shellystore.co.uk/product/shelly-pro-3em/

**Comment by SteveBrailsord** [comment]
It’s only the energy going to charge the car I need, (everything else I can
get real time from my inverter or grid meter )

I just wondered if there was a way to talk directly to the myenergi hub ?

**Comment by G6EJD** [comment]
You can’t communicate with the Hub (the protocols used by MyEnergi have not been reverse engineered), you could monitor the local network traffic to-from the Hub but the protocol is unknown and encrypted.
So not possible.
You get total charge energy from h1b and h1d

**Comment by LeiChat** [comment]
Fingers crossed myenergi will enhance their firmware in the future to support local connectivity.

**Comment by CJNE** [comment]
Local access would be awesome but as @G6EJD pointed out unfortunately not possible at the moment.
