### ISSUE TITLE
Reset eddi "Energy consumed session"

### ISSUE THREAD

**Issue by dannytsang** [CJNE/ha-myenergi#342]
**Is your feature request related to a problem? Please describe.**
I'm using the energy consumed session for the eddi to see how much electricity has been used. The value of the sensor does not reset unless I restart Home Assistant or when eddi consumes electricity the next day.

**Describe the solution you'd like**
Documentation could describe what is a session.

Feature wise, if the session could reset after x seconds/minutes when there is no usage and a sensor for the day and resets at midnight local time.

**Describe alternatives you've considered**
As a workaround, I am going to create a template sensor that has the same value as the eddi energy session and either a trigger or automation to reset it at midnight.

**Additional context**
Screenshot of what my sensor looks like now.
![image](https://user-images.githubusercontent.com/567982/227493093-4dd342d3-9796-4eb2-bf3f-26f8405b062a.png)

**Comment by G6EJD** [comment]
Isn’t your alternative the way Home Assistant is supposed to be used rather than adding many ad-hoc ideas?

**Comment by dannytsang** [comment]
There wasn't much more guidance on the type of alternatives when I was raising the feature request so was there something else I needed to put down?

**Comment by CJNE** [comment]
Thanks for the suggestion @dannytsang. I'm not 100% sure what they mean by session here, the integration just takes the value it gets from the myenergi API. 

The primary goal for this integration is to make all myenergi data available to HA for further processing (if needed).
It sounds like what you're trying to achieve could be solved by adding a helper entity, perhaps a utility meter? 
If things can be solved using HA building block that is the preferred way.  
I'm open to adding custom logic/processing, but that should be as a last resort if there is something that can't be solved in HA.

Pleas let me know if you can get it working with a utility meter helper, it could be useful for others as well, perhaps we can have a wiki with recipes for things like this.

**Comment by dannytsang** [comment]
Makes sense and thank you @CJNE

I will report back and close this off once I confirm if it's working or not.

**Comment by dannytsang** [comment]
@CJNE that worked. Thank you.

This was the setup for anyone else interested:
1. Go to Settings, Devices & Services
2. Go to the Helpers Tab.
3. Create a new helper
4. Add the consumption entity and set your reset cycle. I wanted it to reset to 0 every day so I chose daily.
5. Ignore the warning for **Supported tariffs**
6. Give it a name and submit to save the helper.
![image](https://user-images.githubusercontent.com/567982/228278881-a41f452d-18e3-4d14-9b56-09af5a5b516f.png)

**Comment by CJNE** [comment]
Good to hear you got it sorted, nice solution with the utility meter helper, thanks for sharing!
