### ISSUE TITLE
Is a hub required?

### ISSUE THREAD

**Issue by rossdargan** [CJNE/ha-myenergi#374]
I'm about to get a zappi installed, but my understanding is it now has wifi and doesn't need a hub for the app to work. Do I need a hub however if I want this integration to work?

**Comment by AJediIAm** [comment]
https://community.home-assistant.io/t/myenergi-integration/397716 might be a better place for these kind of questions.

To answer your question: 
The integration uses a MyEnergi cloud API. Both Zappi v2 with hub and Zappi v2.1 with build in wifi connect to this could service. 
You don't need a hub.
