### ISSUE TITLE
Set charge power level of the Zappi

### ISSUE THREAD

**Issue by Annaka007** [CJNE/ha-myenergi#382]
Is there any way to set the output power level of the Zappi, ie I can output 4kW from my home solar batteries therefore would like to put this amount into the car, without having to put the full 7kW. (3 from grid + 4 from batteries) I think you can do it manually by limiting the output power on the unit, but then you need to rest it for a full charge over night, it would just be nice to be able to do this from Home Assistant
Regards Annaka

**Comment by G6EJD** [comment]
In short no. The Device Limit can only be set using the Zappi menu. Don't forget the Zappi can't limit the power delivery to the EV it is the EV that charges (not the Zappi) the best the Zappi can do is set the Control Pilot.

**Comment by G6EJD** [comment]
This should be closed as it’s not an integration issue, the Zappi does not support this function.

**Comment by rastislavpapp** [comment]
uhm, isn't it what it is doing when on eco+ mode, matching the charging power to the solar overflow? :)

**Comment by G6EJD** [comment]
No, it’s not that simple. The Zappi control of the PWM signal to the EV is not exposed in the API and no-one knows if the Zappi design enables control of the PWM, I doubt it does.
There’s a presumption that everything is controllable via the API, but clearly it isn’t.

**Comment by LeiChat** [comment]
Agree with @G6EJD that this issue should be closed.
Functionality not available through myenergi's API so impossible to implement within this integration.

**Comment by G6EJD** [comment]
This issue needs to be closed by the instigator - @Annaka007
