### ISSUE TITLE
Integration setup aborts with “invalid handler specified”

### ISSUE THREAD

**Issue by pichel3000** [CJNE/ha-myenergi#388]
## Version of the custom_component
0.0.23
-->

## Configuration

```yaml
Add your logs here.
```

## Describe the bug
myenergi integration failed to connect for 2 days now. When reloading and disabling did not help, I tried to reinstall. I re-downloaded myenergi from HACS, then restarted HA. When attempting to configure myenergi as an Integration, I get the above message and the configuration is aborted. 

## Debug log

```text

Add your logs here.

```

**Comment by G6EJD** [comment]
Your using the Hub Serial Number and API key?

**Comment by pichel3000** [comment]
Yes, I was. Until the integration stopped working. Now it doesn’t get as far as showing the “Configuration” tab anymore. “ Config flow could not be loaded: {"message":"Invalid handler specified"}”. 

I’ve tried removing the HACS add on, downloading again, restart HA, but the problem remains the same. I’ve checked the folders under custom_components/myenergi are removed once I’ve uninstalled the HACS add on. 

Log entry is: 
Logger: homeassistant.config_entries
Source: config_entries.py:874 
First occurred: 21:55:56 (2 occurrences) 
Last logged: 21:57:24

Error occurred loading flow for integration myenergi: cannot import name 'MyenergiClient' from 'pymyenergi.client' (/usr/local/lib/python3.11/site-packages/pymyenergi/client.py)

**Comment by pichel3000** [comment]
Based on the above file path I had a look after another reinstall and I noticed that the folder “pymyenergi” under site-packages is missing. This might explain the error.

**Comment by pichel3000** [comment]
This is now resolved. I had to completely uninstall HACS, reinstall HACS and then reinstall the Myenergi integration in HA.

**Comment by G6EJD** [comment]
Then you can close it now.

**Comment by pichel3000** [comment]
.
