### ISSUE TITLE
How to change API key in add-on?

### ISSUE THREAD

**Issue by reedy** [CJNE/ha-myenergi#400]
**Is your feature request related to a problem? Please describe.**
I don't see any obvious way on how to change an API key after adding it.

Do I need to add a new integration entity (and then update every sensor/entity usage)? Can I just change it somewhere in config?

**Describe the solution you'd like**

Documenting how to change the API key would be good as a minimum. 

Potentially even including a way on the "Configure" page to replace/override the API key would be very useful.

**Describe alternatives you've considered**

**Additional context**
Security issues happen... myenergi may need to reset them some day, you may share it (accidentally or on purpose) with someone you no longer want to have access to the device(s)...

**Comment by G6EJD** [comment]
This is really easy to do, I’ve done it many times, I just remove the integration, then re-add then enter the new credentials and then everything comes back unaltered. No need for an option to do that.

**Comment by G6EJD** [comment]
You can make the necessary readme amendments and submit it here as a change

**Comment by reedy** [comment]
I can, indeed. As I've submitted other PR's to it previously (and a different one today, too!) ;)

But the issue was originally posed from not knowing the answer.

Adding an option to do it would still make the workflow easier for users anyway. Removing stuff from HA, with unknown consequences of doing so isn't always the most appealing idea. You don't generally expect to have to delete something and re-add it to change a password, for example.

Hub Serial numbers could change too, in case of warranty replacements etc. Especially as they're now integrated into the eddi/zappi devices, but that will result in new/"different" sensors, and things needing updating. I'm not sure a workflow of being able to "change" it would make any sense though.

**Comment by reedy** [comment]
![Screenshot 2023-09-08 at 12 28 13](https://github.com/CJNE/ha-myenergi/assets/67615/abe47488-bf4b-4e00-a23e-14990b378498)

**Comment by AJediIAm** [comment]
Compliments for the nice bug report and taking action to update the documentation. I always appreciate users who take their time to communicate their issues with the developers.

Updating IP address or credentials is commonly done by removing and adding a device in Home Assistant. This is not a MyEnergy specific problem. 
There are a number of feature requests on the HA Community Forum to facilitate these changes better which you can vote on.

**Comment by reedy** [comment]
> Updating IP address or credentials is commonly done by removing and adding a device in Home Assistant. This is not a MyEnergy specific problem. There are a number of feature requests on the HA Community Forum to facilitate these changes better which you can vote on.

I've not looked how they store it, but https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/ actually lets you view (probably not the best idea, I know), and edit the Api key.

But now you mention it, I think that's the only such case of integrations I've used that does allow it like that... Everything else is write only at install/configure time...

**Comment by reedy** [comment]
Closing this as resolved. The docs are updated, so until something better happens upstream in HA, I think this is good enough
