### ISSUE TITLE
Sample Documentation on how to change charge mode in Nod-Red

### ISSUE THREAD

**Issue by russellevans** [CJNE/ha-myenergi#414]
This may be me just missing the obvious....in which case please accept my apologies
Could you add example documentation on how to change the charge state in Node-Red

In developer tools I can set state for "select.myenergi_zappi_20502289_charge_mode"
Options Fast, Eco, Eco + & Stopped

In the node-red "Change State" node I have tried to find the charge mode to set it but have not been able to get it work.

I have considered making some change in YMAL but I am lost as to what to do.

I am running Home Assistant Core 2023.9.1 in VM running on Proxmox

This is very useful custom intergration ......thank you for putting it together!!

**Comment by reedy** [comment]
If someone doesn't beat me to it, I might get round to doing this too... Playing with Node-RED is on my near term TODO list
