### ISSUE TITLE
Harvi usage not being able to be used on energy dashboard (power ct grid)

### ISSUE THREAD

**Issue by sixpack-de** [CJNE/ha-myenergi#441]
Hi,

utilizing myI want to utilize my Harvi output as an Input device for the energy dashboard (as this is the only device currently connected "outbound".

I do not have debug logging :)

I have a Harvi with Harvi Firmware: 3170S0.000, installed the latest via HACS.

I cannot select my "power ct grid" entity, and reason is given under: "https://www.home-assistant.io/more-info/statistics/"
--> "_Integrations need to configure their entities correctly so Home Assistant knows that we need to track statistics for it and how._"

```

**Comment by trizmark** [comment]
The CT output of your harvi is an instant meaurement (W); the energy dashboard requires energy over time (Wh).
You simply need to add a Riemann sum integral helper with the power ct grid as the input. (https://www.home-assistant.io/integrations/integration/) I'd suggest selecting the 'Left Riemann sum' integration method.
You'll be able to use the created entity in the energy dashboard. (You might need a few minutes to have enough data)

**Comment by sixpack-de** [comment]
Thanks, the solution works, the HACS guidance somehow misleading. 
Important is that the metric prefix is set to k (kilo) and time unit to hours.

Thanks again,

Jan
