### ISSUE TITLE
Wrong link shown in the connection page

### ISSUE THREAD

**Issue by matinciel** [CJNE/ha-myenergi#473]
## Version of the custom_component

Version 0.0.24

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

The link in the description when adding the integration is NOT the good one

![link_issue_when_adding_intergation](https://github.com/CJNE/ha-myenergi/assets/39257302/08b02905-43ea-4247-b446-91facf9ac7b5)

it's : 
https://github.com/cjne/myenergi 
it should be (o maybe some other page to help the user determining what to put there) : 
https://github.com/CJNE/ha-myenergi

Clicking the question mark (top right corner) works ok.

**Comment by jwillemsen** [comment]
Should be fixed now
