### ISSUE TITLE
Harvi CT clamps no longer capturing data, stuck on old reading.

### ISSUE THREAD

**Issue by juscode** [CJNE/ha-myenergi#492]
<!-- Before you open a new issue, search through the existing issues to see if others have had the same problem.

Issues not containing the minimum requirements will be closed:

- Issue started at 10:30am on 28/02/2024, effects CT1 and CT2 sensors.
- Harvi still showing CT readings on Zappi.
- Updated to latest release of myenergy for Home Assistant 0.0.25
- Not seeing any errors on the Logs

```

**Comment by G6EJD** [comment]
This will not be an issue with this integration, your system has a corrupted setup which you need to fix.

**Comment by juscode** [comment]
I can't see any issues in the logs and everything was working literally fine until 10:30am with no updates or change to hardware.

**Comment by G6EJD** [comment]
Mine is working perfectly, so not a server issue. 
1. Are both Harvi flashing 1/sec?
2. Are both Harvi visible on the Linked Devices screen?

**Comment by juscode** [comment]
Yes Harvi is flashing a green light every second, when I go into the Zappi I can see the live CT clamp data from each of the CT clamps from the Harvi, only other thing I've noticed is that the Harvi is appearing as offline in the MyEnergy my account dashboard, is this also the same for you ?

**Comment by juscode** [comment]
Raised a ticket with MyEnergy who seem to have solved it, Harvi is back in the MyEnergy dashboard and in HA thanks for your help anyway.
