### ISSUE TITLE
Add feature to select 1/3/auto phases to be used in ECO+ mode

### ISSUE THREAD

**Issue by jwillemsen** [CJNE/ha-myenergi#509]
**Describe the solution you'd like**
The latest zappi app has support to set the number of phases to be used in ECO+ mode (see https://myenergi.info/app-update-3-3-1-t12674.html#p122029)., can be 1, 3, or auto

**Additional context**
See https://github.com/CJNE/pymyenergi/issues/28 for the pymyenergi related issue

**Comment by heikone** [comment]
Would be a great feature, because the integrated solution of Zappi, when setting is "auto", is sometimes not a good choice. In my case and at partly clouded weather, the Zappi is spending more time waiting to change from one to three phase and back, than it would charge constantly at one phase. Especially, when other consumers switch on and off. 
Greetings, Heiko

**Comment by jwillemsen** [comment]
I have asked myenergi on the API, no feedback yet

**Comment by G6EJD** [comment]
That’s because you can’t switch phases.

**Comment by G6EJD** [comment]
This can’t be achieved in a Zappi or any other EVSE, don’t should be closed

**Comment by jwillemsen** [comment]
The myenergi app does provide the ability to select 1/3/auto phase charging in ECO+ mode, a recent addition of the app.

**Comment by jwillemsen** [comment]
![Schermafbeelding 2024-05-08 om 15 41 58](https://github.com/CJNE/ha-myenergi/assets/47353/0d93632b-07bc-4f80-9eb1-8785998ffcf4)

**Comment by G6EJD** [comment]
Yes, but titles need to be clear and now it has been changed!

**Comment by jwillemsen** [comment]
I will implement this asap

**Comment by phhoef** [comment]
not sure if it helps. I monitored the requests and found out the command for phase switching.
I mentioned it in the other GitHub project describing the API:
https://github.com/twonk/MyEnergi-App-Api/issues/25

**Comment by heikone** [comment]
Dear all,
just want to ask about the progress of this?
Background is, that the automatic switching by Zappi does not work very well (sometimes the system is taking more time switching than loading :-). 
Therefore, my plan is do something more clever with automations from Homeassistant. For example much longer retention time of phase before switching from 1 to 3-phase loading.
Anyway, this requires the possibility to switch in HA.

Does anybody observe the same problem with Zappi's automatic switching?
Any advice, if setting in Zappi can be adjusted?

Best regards,
Heiko

**Comment by jwillemsen** [comment]
The code necessary is ready for review on my PR.

**Comment by erikgeurts** [comment]
> The code necessary is ready for review on my PR.

For some reason, one of the automatic checks is failing (pre-commit). I am not sufficiently experienced with Github to figure out which file(s), and what's the reason it fails. Perhaps have a look at that, because it seems that once this check is OK, the PR could be pushed through.

**Comment by jwillemsen** [comment]
I think two linters are making opposite changes, also happens in the scheduled action, so not related to my PR

**Comment by erikgeurts** [comment]
> I think two linters are making opposite changes, also happens in the scheduled action, so not related to my PR

Since I don't even know what a 'linter' is, I can't help with that. Is there someone else who could look into this and figure out what's causing the check(s) to fail? Perhaps the person who created the scheduled actions.
