### ISSUE TITLE
Deprecation warning with HA 2024.5.0

### ISSUE THREAD

**Issue by jwillemsen** [CJNE/ha-myenergi#528]
## Version of the custom_component

[Version 0.0.27](https://github.com/CJNE/ha-myenergi/releases/tag/0.0.27)

## Describe the bug

Got the following warning in the HA log:

`Detected that custom integration 'myenergi' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/myenergi/__init__.py, line 57: hass.async_add_job(, please create a bug report at https://github.com/cjne/ha-myenergi/issues`

**Comment by trizmark** [comment]
This is a duplicate #510
