### ISSUE TITLE
automatic/1/3 phase charging switch

### ISSUE THREAD

**Issue by Chawiby** [CJNE/ha-myenergi#545]
Hi,
In the app there is the opportunity to sitch between 1 phase, 3 phase charging or automatic switch. It would be great if this feature could also be added to the Home Assistant integration. Thank you!
PS: Of course, this works for 3 phase Zappis only.

![image](https://github.com/CJNE/ha-myenergi/assets/117714758/02cade76-200b-4088-a860-4f4740d28300)

**Comment by heikone** [comment]
Reder to this post:
[](https://github.com/CJNE/ha-myenergi/issues/509)

Greetings,
Heiko

**Comment by Chawiby** [comment]
Thank you!-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 22.06.24, 18:47 schrieb Heiko Neuberger ***@***.***>:

   
  Reder to this post:  
  Greetings, Heiko

**Comment by CJNE** [comment]
Fixed in 0.0.28, thanks!
