### ISSUE TITLE
Only one Entity shown

### ISSUE THREAD

**Issue by Jogiarea** [CJNE/ha-myenergi#61]
Hello and first of all thank you for the project, myenergy gets unfortunately no HASS API baked ;-)

I have installed it manually and I was able to log in, unfortunately only one entity is displayed and only that of the charging mode.

Am I doing something wrong?
![1](https://user-images.githubusercontent.com/86875561/147233287-16267693-73ed-47be-9283-7b296061f99e.PNG)

**Comment by G6EJD** [comment]
When you go to HA Configuration, then Devices and Services, what do you see for myenergi Devices and Entities?

are you using the latest HA?

have you restarted the Host?

**Comment by Jogiarea** [comment]
Hi 
yes I restartet The host and the Hole server (Docker) but nothing happens

On Config - Devices and services:
![2](https://user-images.githubusercontent.com/86875561/147233452-b85311f8-ebc2-43e4-b1ca-1d9fd4de4838.PNG)

My Hass Version is
![3](https://user-images.githubusercontent.com/86875561/147234015-e4e382bd-70c2-4f2c-990b-96a5d509f8c7.PNG)

**Comment by G6EJD** [comment]
Have you installed the supporting Python scripts?

**Comment by Jogiarea** [comment]
What do I have to install?
https://github.com/cjne/pymyenergi
This one?

How can i install this in docker?

**Comment by G6EJD** [comment]
I install - File Editor, then at the command prompt follow the instructions here.

**Comment by CJNE** [comment]
You should not have to install the library yourself, Home Assistant will handle that for you.
In the latest version I added entity categories:

https://www.home-assistant.io/blog/2021/11/03/release-202111/

So for zappi only the charge mode should be added to Lovelace by default. But all other entities should show up when you look at the device, so it sounds like something went wrong when the integration was configured.

Can you try to remove the integration and add it again?
The take a look in the log to see if there are any error messages.

**Comment by Jogiarea** [comment]
Dankle you now it runs 1a
Have first HASS brought up to date.
has first brought nothing
Then I created the entity again and lo and behold it runs 1a

Thank you very much and Merry Christmas to you
