### ISSUE TITLE
Hole in the data

### ISSUE THREAD

**Issue by Ulrar** [CJNE/ha-myenergi#74]
## Version of the custom_component

Latest from HACS

## Describe the bug

The various entities don't show any data for a few hours this morning, and did not backfill.
My understanding was that sometimes the hub might disconnect, or the API might be down, but data would then automatically be backfilled. I checked the myenergi app and I do have data for these hours, so the hub must have sent the data out at one point or another, but the HA integration isn't backfilling it.

See below screenshot from the energi hub grid import today entity, that flat line between 1:20am and 9:17am has no data.
![image](https://user-images.githubusercontent.com/873423/149953823-40a6a2c5-c7dc-4cda-89f0-a3d9b2677bda.png)

Is there a way to force a backfill, maybe a service I could call to have the integration re-fetch that time slice ?
Thanks

**Comment by CJNE** [comment]
Hello @Ulrar 
This is not really the way things work in HA, if a sensor loose connectivity then no data is recorded in HA for the duration which leads to gaps, there's no way to backfill data.
In this case with an energy meter sensor it's not that bad, the total will still be correct for the day, it's just looks a little bad in the graph.
