### ISSUE TITLE
Sensor showing good graph info in "History" but not available to add to "Energy" panel

### ISSUE THREAD

**Issue by ccomley** [CJNE/ha-myenergi#80]
## Configuration

```yaml
Add your logs here.
```

## Describe the bug

Thanks to CJNE for helping me find and install this. 
It's pulling the info we need from the Myenergi system, and showing it on the graphs in "History". 
However we would like to see the data in the "Energy" tab. 
We have successfully added to that the "myenergi accountname Grid Import Today" and "myenergy accountname Generated Today" entries, and the Energy panel shows sensible results from that source data.  
In similar vein we have added "myenergi zappi<serno> Charge added session" and it is showing power sent to the car. 

We have an additional CT on the Harvi - it actually monitors the power sent to our ASHP home heating system. Myenergi don't have a way to describe that to the system so we've picked "Battery".

The "History" graph picks up "Myenergi accountname Power Battery" and the graphed data - whilst showing negative, is showing a credible curve, based on the times the heating comes on, what it does, etc. 

So the final piece in our puzzle is to add this object to the Energy config. But it does not appear on the list of things we can choose to add! 

The sensor name, from the main config, appears to be "sensor.myenergy_accountname_power_battery"

I'm unclear what logs or config files you are asking to be appended to this note. 

## Debug log

```text

Add your logs here.

```

**Comment by CJNE** [comment]
Hi @ccomley 
I'm glad you finally managed to get it up and running!
The energy panel can only handle sensors that measure energy (kWh), the one you're trying to add measures power (W).
You can read more about this topic here: https://www.home-assistant.io/docs/energy/faq/
As described there you can make an energy sensor with a power sensor as source, using the integration sensor:
https://www.home-assistant.io/integrations/integration/#energy
