### ISSUE TITLE
Negative power generation 

### ISSUE THREAD

**Issue by JanDetrez** [CJNE/ha-myenergi#81]
Any idea why the power production in Hassio shows negative values, while this is not the case in the Myenergi app?

![Screenshot_20220129-191627](https://user-images.githubusercontent.com/16916740/151672662-e46cd3e6-8a3c-4eb6-91ca-78e7d32b6144.png)
![Screenshot_20220129-191610](https://user-images.githubusercontent.com/16916740/151672663-af846a1b-9716-44d5-8f1f-baf4761e3191.png)

**Comment by JanDetrez** [comment]
FYI in the Energy tab the negative values are not visible 
![Uploading Screenshot_20220129-191925.png…]()

**Comment by G6EJD** [comment]
Where is the data coming from? I get negative values (transients) from the GivEnergy server API, I presume ME filter all negative values, but on mine I see the night time power draw of the inverter when it’s in standby about 20W.
Do you have anyway of seeing the raw data from the inverter?

**Comment by JanDetrez** [comment]
The power generation value plot I show above is coming directly from ME, which is clamped via a Zappi to the solar AC power cables.

Good point that this may actually be power draw from the inverter. I looked around in the app and web portal of my PV system, but couldn't find a measure for this. Also, as opposed to a 20 W continuous standby draw you talk about, mine seem to be isolated draws of about 100 W. You could still be right, but the profile seems a bit odd to me.

**Comment by G6EJD** [comment]
My Solaredge inverter takes a varying amount of power, 20W is more like an average, it moves around the values of 5 to 10 to 20 then 10, it will depend on your inverter design, but a sudden in-rush of power at reasonably regular intervals would not be unusual. You could try running the Python at the command prompt and see if the API is returning the negative values, I’m sure it will do if the readings exist and it’s not some other artefact.

**Comment by JanDetrez** [comment]
Okay thanks for the feedback.

I'm not sure to which code you are referring, but I suppose it is a piece that gets the current values from ME? I can have a look, but to see the negative current, I suppose I would need to run the script exactly timed with a spike, which seems difficult to achieve.

**Comment by G6EJD** [comment]
Johan provides some Python scripts that can be run from the HA command line, it would be interesting to see if there was a negative current being reported. Yes difficult to capture an event that is not synchronous.
On the basis that most users are not reporting negative current spikes and ME probably suppresses them then it looks they are real and due to the inverter taking grid power when in sleep mode.

**Comment by JanDetrez** [comment]
Ok, thanks for the feedback. That solves for me the 'issue'.
